/** Language ids follow VS Code's (`typescript`, `python`, `dockerfile`, …), `plaintext` otherwise. */

const BY_NAME: Readonly<Record<string, string>> = {
  dockerfile: 'dockerfile',
  containerfile: 'dockerfile',
  makefile: 'makefile',
  gnumakefile: 'makefile',
  cmakelists: 'cmake',
  'cmakelists.txt': 'cmake',
  jenkinsfile: 'groovy',
  gemfile: 'ruby',
  rakefile: 'ruby',
  podfile: 'ruby',
  vagrantfile: 'ruby',
  justfile: 'just',
  procfile: 'plaintext',
  '.gitignore': 'ignore',
  '.dockerignore': 'ignore',
  '.npmignore': 'ignore',
  '.gitattributes': 'properties',
  '.editorconfig': 'properties',
  '.bashrc': 'shellscript',
  '.zshrc': 'shellscript',
  '.profile': 'shellscript',
};

const BY_EXT: Readonly<Record<string, string>> = {
  ts: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  tsx: 'typescriptreact',
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'javascriptreact',
  json: 'json',
  jsonc: 'jsonc',
  json5: 'json5',
  py: 'python',
  pyi: 'python',
  go: 'go',
  rs: 'rust',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  scala: 'scala',
  groovy: 'groovy',
  gradle: 'groovy',
  c: 'c',
  h: 'c',
  cc: 'cpp',
  cpp: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  hh: 'cpp',
  cs: 'csharp',
  fs: 'fsharp',
  swift: 'swift',
  m: 'objective-c',
  mm: 'objective-cpp',
  rb: 'ruby',
  php: 'php',
  pl: 'perl',
  lua: 'lua',
  r: 'r',
  dart: 'dart',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hs: 'haskell',
  clj: 'clojure',
  ml: 'ocaml',
  zig: 'zig',
  nim: 'nim',
  sh: 'shellscript',
  bash: 'shellscript',
  zsh: 'shellscript',
  fish: 'fish',
  ps1: 'powershell',
  bat: 'bat',
  cmd: 'bat',
  sql: 'sql',
  prisma: 'prisma',
  graphql: 'graphql',
  gql: 'graphql',
  proto: 'proto3',
  html: 'html',
  htm: 'html',
  vue: 'vue',
  svelte: 'svelte',
  astro: 'astro',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  md: 'markdown',
  mdx: 'mdx',
  rst: 'restructuredtext',
  txt: 'plaintext',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  ini: 'ini',
  cfg: 'ini',
  conf: 'properties',
  properties: 'properties',
  env: 'dotenv',
  xml: 'xml',
  svg: 'xml',
  tf: 'terraform',
  tfvars: 'terraform',
  hcl: 'hcl',
  nix: 'nix',
  dockerfile: 'dockerfile',
  mk: 'makefile',
  cmake: 'cmake',
  csv: 'csv',
  lock: 'plaintext',
};

/** Language of a workspace path, from its file name or extension. */
export function detectLanguage(path: string): string {
  const name = path.slice(path.lastIndexOf('/') + 1).toLowerCase();
  const byName = BY_NAME[name];
  if (byName) return byName;
  if (name === '.env' || name.startsWith('.env.')) return 'dotenv';
  if (name.startsWith('dockerfile.') || name.endsWith('.dockerfile')) return 'dockerfile';
  const dot = name.lastIndexOf('.');
  if (dot <= 0) return 'plaintext';
  return BY_EXT[name.slice(dot + 1)] ?? 'plaintext';
}
